### ISSUE TITLE
Where should [multicolour] topic icons live?

### ISSUE THREAD

**Issue by callumlocke** [Financial-Times/o-ft-icons#123]
The Next [FastFT stream](https://next.ft.com/fastft) uses a branding icon in the header, which comes from o-ft-icons (via `nextIcon('brand-fast-ft')`, via next-sass-setup).

![image](https://cloud.githubusercontent.com/assets/250617/13878941/8ce6bad2-ed0c-11e5-89ad-a0d9561394e9.png)

The Next [Brexit stream](https://next.ft.com/brexit) also has an icon, but this is currently hosted on our IG webserver, and we'd like to put it somewhere more proper:

![image](https://cloud.githubusercontent.com/assets/250617/13878973/c79e19ea-ed0c-11e5-91f0-44bcdcd35053.png)

The issue is it's multicolour (also this one happens to be a PNG for some reason), making it different from everything else in o-ft-icons, so I'm guessing this isn't the right place for it.

We've also got a similar icon coming up very soon for the US Presidential Election. Where should these kind of graphics live?

**Comment by alicebartlett** [comment]
This is a good question, let's kick it around the Origami Open Meeting on 24th at 2pm and see what we come up with. I'll add it to the agenda, will add you to the calendar invite but feel free to skip if you're busy.

**Comment by sumeetadur** [comment]
Todo:

![screen shot 2016-03-22 at 10 37 45](https://cloud.githubusercontent.com/assets/15633037/13948821/32dd9c16-f01a-11e5-9761-0e037087bf4b.png)

**Comment by AlbertoElias** [comment]
We're going to create this repo, not sure about the naming, our current image sets are:  headshot-images, social-images, podcast-logos, o-ft-icons

Suggestions?

Maybe logo-images or ft-logos?

cc @callumlocke @SarahHornsey

**Comment by SarahHornsey** [comment]
How about: headshot-images, social-logos, podcast-logos, o-ft-logos

**Comment by AlbertoElias** [comment]
@SarahHornsey we can't really rename the current ones as that could break things, we just need a name for the new repository

**Comment by AlbertoElias** [comment]
https://github.com/Financial-Times/logo-images has now been created. Feel free to push things there, we're working on adding this to the image service

**Comment by onishiweb** [comment]
@AlbertoElias can we close this now that we have `logo-images`?

**Comment by AlbertoElias** [comment]
Yes!
