### ISSUE TITLE
move next.ft.com icons out of next branch

### ISSUE THREAD

**Issue by alicebartlett** [Financial-Times/o-ft-icons#126]
![screen shot 2016-03-22 at 10 18 51](https://cloud.githubusercontent.com/assets/68009/13948641/12734c42-f019-11e5-9756-be094be94b28.png)

These are the icons that are currently in the next branch. We'd like to move the ones that are actually in use on next into master, this will involve the following work:

Pass through svgomg
Normalise the bounding box size
Normalise the names
Normalise the path colour
Test with the png conversion on the image service

**Comment by AlbertoElias** [comment]
Closed by #124
