### ISSUE TITLE
Add "external link" icon

### ISSUE THREAD

**Issue by callumlocke** [Financial-Times/o-ft-icons#15]
e.g. for links that we might open in a new tab.

http://fortawesome.github.io/Font-Awesome/icon/external-link/

**Comment by kaelig** [comment]
@callumlocke if this is still needed, can you have a chat with designers about this? (or close the issue)

**Comment by callumlocke** [comment]
@sdbernard could you knock up an external link icon?

**Comment by alicebartlett** [comment]
@callumlocke we're about to refactor o-ft-icons, we'll remove some unused icons and add some more in. HHM if you still want an external link icon, and can get it from @sdbernard and we can add it in as part of this work.
