### ISSUE TITLE
Provide before and after placeholder classes and options for the mixin

### ISSUE THREAD

**Issue by wheresrhys** [Financial-Times/o-ft-icons#2]
For the ft header I want to use `:after` to add the icon. Can the placeholders come in both flavours e.g `%o-ft-icons--icon-profile` = `:before` and `%o-ft-icons--icon-profile--after` = `:after`? And also another parameter for the mixin to specify before or after (defaulting to before).

**Comment by kaelig** [comment]
Fixed in #28.
