### ISSUE TITLE
Source icon vector file

### ISSUE THREAD

**Issue by pauloneillft** [Financial-Times/o-ft-icons#23]
I've collated (as best I can) all of the FT icons into a single source file. It seems logical for this source vector file to live in the repo with all the o-ft-icon stuff.

I also created documentation for designers on how to create icons and manage them within Adobe Illustrator. This could be stored in the repo too.

@kavanagh , might be of use to IG too.

@triblondon what do you think?

**Comment by kaelig** [comment]
> I also created documentation for designers on how to create icons and manage them within Adobe Illustrator. This could be stored in the repo too.

@pauloneillft have we included this in the repo? If not, how can I help?
