### ISSUE TITLE
Remove logos from module

### ISSUE THREAD

**Issue by AlbertoElias** [Financial-Times/o-ft-icons#27]
I've been speaking with @kavanagh about this, and we also had [this issue on o-ft-header](https://github.com/Financial-Times/o-ft-header/issues/39) and maybe it would be a good idea to remove logos from this module, which would also make the module itself less heavy. These should probably be pulled from the image service.

**Comment by kaelig** [comment]
Closing this as there hasn't been any updates in 6 months.
