### ISSUE TITLE
Document how to use $o-ft-icons-path or $o-assets-global-path

### ISSUE THREAD

**Issue by callumlocke** [Financial-Times/o-ft-icons#39]
There doesn't seem to be any mention of these variables in the readme.

I get cross-origin errors in Firefox if I don't set one of these variables to `../bower_components/`

@sdbernard

**Comment by kaelig** [comment]
/ping @callumlocke is this still an issue?

**Comment by callumlocke** [comment]
Sorry! I think this is out of date now...
