### ISSUE TITLE
Add icons for save, upload, download, star, unstar

### ISSUE THREAD

**Issue by wheresrhys** [Financial-Times/o-ft-icons#45]
Ones that spring to mind are
 - save
 - upload
 - download
 - favourite (hollow and filled stars)

There are a lot of icons here https://useiconic.com/open#icons which would be useful to have FT equivalents of too

**Comment by triblondon** [comment]
@wheresrhys still keen?

**Comment by wheresrhys** [comment]
What an ancient issue! I think there is a broader family of issues of which this is a small part

 - Rename icons to sensible names  - e.g. arrow-down and arrow-downwards are unhelpful. Given we have a chance to start afresh with a major release we should review. 
- Maybe have a cull of icons which we guess aren't widely used (put a bold notice at the top of the readme 'If you need an icon from v3 which isn't in v4 please speak to the origami team')
- If after the above there are some common use cases not covered (particularly within next) create icons for them

I really think it's a missed opportunity if we don't get rid of some cruft in the v4 release
