### ISSUE TITLE
Change twitter icon

### ISSUE THREAD

**Issue by pauloneillft** [Financial-Times/o-ft-icons#50]
This is different to the twitter icon that already exists. The one that already exists is for the webapp use-case only.

Email with SVG attachment sent to origami.support Nov 25th 2.55pm
![screen shot 2014-11-25 at 14 55 57](https://cloud.githubusercontent.com/assets/3977053/5184919/2d16a0b8-74b3-11e4-95f1-d10aed42ec2b.png)

**Comment by triblondon** [comment]
Is this still relevant, @pauloneillft ?
