### ISSUE TITLE
Add lock icon

### ISSUE THREAD

**Issue by roland-vachter** [Financial-Times/o-ft-icons#56]
It's for comments for now, but it is also a generic icon that can be considered.

An example article (see comments section): http://www.ft.com/intl/cms/s/0/9a3efede-7fc5-11e4-acf3-00144feabdc0.html?siteedition=intl#axzz3LalBVPn8
The current icon: http://www.ft-static.com/sp/prod/comments/3.2.0/long/resources/o-livefyre-comment-client/src/images/comment_locked.png

**Comment by alicebartlett** [comment]
Can I close this @roland-vachter @pauloneillft ?
We're about to update o-ft-icons with new icons for next happy to add in other icons too if they're needed.

**Comment by roland-vachter** [comment]
Was that icon added to o-ft-icons?

**Comment by alicebartlett** [comment]
http://registry.origami.ft.com/components/o-ft-icons I don't see it here if it was

**Comment by roland-vachter** [comment]
Then I don't think this issue can be closed.

**Comment by pauloneillft** [comment]
I think we can close this. Mea colpa, I should have chased this up (although it is up to the individual designers who create these icons to do their due diligence and put them into Origami!) I've just noticed the gear wheel icon now too for commenting settings... who created these and why wasn't the origami gear wheel icon used instead of this one? @roland-vachter

**Comment by roland-vachter** [comment]
Hi Paul, this is about the lock icon, not the gear. The gear icon is already used in o-comments.

**Comment by alicebartlett** [comment]
OK, so if there is still a product need for the padlock, then we can keep this issue open. @pauloneillft are you OK to create the padlock icon, or would you like me to find someone else to do it?

@pauloneillft As for the gear, let's move that discussion to another issue on this repo, though from what @roland-vachter is saying it seems like o-comments is using the gear already?

**Comment by roland-vachter** [comment]
Yes, it is using the gear already: o-ft-icons-icon o-ft-icons-icon--settings

**Comment by i-like-robots** [comment]
We have a padlock in the #next branch

**Comment by onishiweb** [comment]
There's a padlock icon in `o-icons` now.

**Comment by alicebartlett** [comment]
🎉
