### ISSUE TITLE
Character encoding issue

### ISSUE THREAD

**Issue by jamesnicholls** [Financial-Times/o-ft-icons#60]
On line 64, character 65 of scss/_mixins.scss, there is an ellipsis character that is causing Sass to fail on Ubuntu 14.04 LTS.

Stack trace:
```
[exec] Syntax error: Invalid US-ASCII character "\xE2"
[exec]         on line 64 of /home/sal/gitroot/sign-up-app/signup-web/bower_components/o-ft-icons/scss/_mixins.scss
[exec]         from line 3 of /home/sal/gitroot/sign-up-app/signup-web/bower_components/o-ft-icons/main.scss
[exec]         from line 3 of /home/sal/gitroot/sign-up-app/signup-web/bower_components/o-ft-buttons/main.scss
[exec]         from line 4 of /home/sal/gitroot/sign-up-app/signup-web/bower_components/o-ft-forms/main.scss
[exec]         from line 6 of src/main/web/files/sass/main.scss
[exec]   Use --trace for backtrace.
```

**Comment by kaelig** [comment]
Thanks for reporting this, it might have to do with the default Ruby encoding on the system.

Here's a range of ways to fix that: http://stackoverflow.com/questions/5967626/ruby-1-9-and-sass-encoding-issues-from-ascii-8bit-to-utf-8

**Comment by jamesnicholls** [comment]
Thanks. Not sure what the exact issue was, but an upgrade of Maven seemed to have fixed the issue.

**Comment by kaelig** [comment]
Thanks @jamesnicholls for the update, I'm closing this issue, then.
