### ISSUE TITLE
next-icons

### ISSUE THREAD

**Issue by wheresrhys** [Financial-Times/o-ft-icons#72]
To eliminate confusion I think we should

 - fork this to 'next-icons', get rid of all the font forge stuff, rename our next branch to master and set up some CI that

1. Makes sure SVGs are tintable (no stroke or fill colours allowed). Some other conditions would be good, e.g. icon must be square unless its name meets some convention we decide upon for describing aspect ratios
2. Triggers a master build of next assets.

@keirog @tom-parker @charypar @kaelig

**Comment by kaelig** [comment]
Fine with me. Please get in touch with @pornel for the image service integration

**Comment by pornel** [comment]
http://image.webservices.ft.com/v1/#tint

**Comment by wheresrhys** [comment]
We could do something clever with versioning if we have our own icon module
e.g. we change next-assets to upload icons to a v1, v2 directory etc., then update the mixin to point there?

**Comment by charypar** [comment]
:+1: this sounds very good to me.

**Comment by triblondon** [comment]
@wheresrhys if you're now adopting o-ft-icons will you be deprecating n-icons? Either way can we close this issue?

**Comment by wheresrhys** [comment]
yep, n-icons was basically gonna be what o-icons@4 now is
