### ISSUE TITLE
Use ligatures for accessible font

### ISSUE THREAD

**Issue by pornel** [Financial-Times/o-ft-icons#75]
Alternative to #54

Instead of using arbitrary characters for the icons it's possible to use ligatures to replace words with symbols (e.g. every occurence of letters "Back" could be automagically displayed as "<").

Here's an example implementation: https://symbolset.com/

This way a text alternative for the icons would always be in the markup, with no CSS hacks needed, and it would also help users who can see, but their browser didn't download the icon font.

![not that](https://cloud.githubusercontent.com/assets/72159/8831125/32227b80-3098-11e5-816f-d4275decfdff.png)

**Comment by triblondon** [comment]
When I've sought advice on a similar theme in the past - whether to use dedicated characters for accents or diacritics combined with the unaccented char, I've been told that the dedicated chars are preferred.  And Léonie Watson told me that her screen reader couldn't understand her name when I typed it using diacritics.  Do assistive tools actually work with the approach outlined?

**Comment by pornel** [comment]
I think you're talking about Unicode normalisation forms - composed vs decomposed characters, but that's a different thing.

Ligatures can be done only at the font level, for example here's Zap, Zapf, Zapfin, Zapfino rendered in Zapfino font without ligatures:

<img src="https://cloud.githubusercontent.com/assets/72159/8834569/df031b84-30ac-11e5-9e19-f9007b45d192.png">

and with ligatures:

<img src="https://cloud.githubusercontent.com/assets/72159/8834577/e7ee7c34-30ac-11e5-82ad-ee4e809c5ce4.png">

It's the same pure ASCII text in both cases.

**Comment by kaelig** [comment]
I think the guys at Lonely Planet used ligatures at some point. I think they had issues with older browsers.

@i-like-robots can you comment on that?

**Comment by i-like-robots** [comment]
We had to ask the font foundry to provide a wide range of extra characters to cover Vietnamese, Icelandic, German etc. but I don't remember any extras for purely style reasons - ff, fl, fi etc. were always rendered with basic characters.

**Comment by kaelig** [comment]
@i-like-robots Thanks, are you referring to font icons or text/type fonts?

**Comment by i-like-robots** [comment]
@kaelig I was referring to text fonts, we didn't use icon fonts

**Comment by kaelig** [comment]
@i-like-robots Ok, cheers.

I can't remember who used ligatures…

IMHO, for accessibility and backwards-compatibility, decorative ligatures aren't that good:

- Browsers that don't support ligatures would see "arrow-down" instead of the glyph (not helpful)
- we'd need to add `role="presentation"` to all of these icons
- Do ligatures work with CSS `content`? Or do they require a plain `<el>text</el>`?

The only case where that might be useful is for a set of weather icons.

**Comment by pornel** [comment]
The ft-app has awful `<button><i/></button>` markup for things like close buttons and next/previous. I'd like to improve that.

AFAIK only IE <= 8 is a problem, but ft-app doesn't support that.

**Comment by triblondon** [comment]
I think we are pretty committed to dropping the icon font at this point so this issue is probably moot.
