### ISSUE TITLE
Syntax Error on obt demo?

### ISSUE THREAD

**Issue by mark-lacdao** [Financial-Times/o-ft-icons#83]
Have been following the steps to build locally, got stuck on executing the command 

`obt demo --runServer`

got the response
```
const argv = require('minimist')(process.argv.slice(2));
^^^^^

SyntaxError: Use of const in strict mode.
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3
```

Any ideas?

**Comment by AlbertoElias** [comment]
What version of obt are you using?

**Comment by mark-lacdao** [comment]
Hello thanks for the prompt response, I'm using `origami-build-tools@4.1.0`

**Comment by AlbertoElias** [comment]
Thanks! And what version of node?

**Comment by mark-lacdao** [comment]
Node version is `v0.12.7`

**Comment by AlbertoElias** [comment]
You need Node v4 or higher to run obt v4, could you give that a go and let
me know if it fixes the error?

-- 

------------------------------
This email was sent by a company owned by Pearson plc, registered office at 
80 Strand, London WC2R 0RL.  Registered in England and Wales with company 
number 53723.

**Comment by mark-lacdao** [comment]
Thanks that fixed it! Error was replaced by

```
Error in plugin 'gulp-sass'
Message:
    demos\src\demo.scss
  1:9  file to import not found or unreadable: o-assets/main
Current dir:
Details:
    column: 9
    line: 1
    file: stdin
    status: 1
    messageFormatted: demos\src\demo.scss
  1:9  file to import not found or unreadable: o-assets/main
Current dir:
```
Will try to poke around for this one, thanks again!

**Comment by AlbertoElias** [comment]
You might need to run bower install?

-- 

------------------------------
This email was sent by a company owned by Pearson plc, registered office at 
80 Strand, London WC2R 0RL.  Registered in England and Wales with company 
number 53723.
