### ISSUE TITLE
new icon - warning icon

### ISSUE THREAD

**Issue by mark-lacdao** [Financial-Times/o-ft-icons#85]
Hi and good day, I have created a new warning icon (see attached for png version).
The icon is in SVG format, and I've followed the instructions [here](https://github.com/Financial-Times/o-ft-icons#add--edit-icons-build-the-web-font-and-demo-page), however when I ran the demo locally using `obt demo --runServer`, all of the icons were not rendering and I noticed that it was looking for non-existent woff and ttf files (see attached screenshot).

Are there any more steps that I should execute in order to add a new icon and also for the icons to be rendered properly?

Thanks in advance.
![1](https://cloud.githubusercontent.com/assets/6408369/10479743/aeafe1c8-7298-11e5-90fc-4bc40756ec2e.png)

![warning](https://cloud.githubusercontent.com/assets/6408369/10479627/f1446b68-7297-11e5-89da-d0a4156bc2d1.png)

**Comment by AlbertoElias** [comment]
This has been done
