### ISSUE TITLE
Masthead svg broken on chrome in windows 7

### ISSUE THREAD

**Issue by alicebartlett** [Financial-Times/o-ft-icons#96]
![screen shot 2015-11-30 at 12 17 42](https://cloud.githubusercontent.com/assets/68009/11471362/c8de42fe-975c-11e5-9bb1-2bc34b362904.png)

This is not a problem in chrome on osx, just windows

**Comment by alicebartlett** [comment]
Interestingly, there are two broken icons on windows 7 chrome, the masthead and the columnists. Both of these icons are the ones that my computer can't compile with font-forge

**Comment by alicebartlett** [comment]
Actually it's all of Windows that it's broken for 😩

**Comment by AlbertoElias** [comment]
@alicebartlett is really great :tada:
